// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ValueConversions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Married")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "F",
                            Gender2 = "Female",
                            Married = true,
                            Name = "Nunezsu"
                        },
                        new
                        {
                            Id = 2,
                            Gender = "M",
                            Gender2 = "Female",
                            Married = false,
                            Name = "Salah"
                        },
                        new
                        {
                            Id = 3,
                            Gender = "F",
                            Gender2 = "Female",
                            Married = true,
                            Name = "Diazgül"
                        },
                        new
                        {
                            Id = 4,
                            Gender = "M",
                            Gender2 = "Female",
                            Married = false,
                            Name = "Fabinho"
                        },
                        new
                        {
                            Id = 5,
                            Gender = "F",
                            Gender2 = "Female",
                            Married = true,
                            Name = "Van Dijknur"
                        },
                        new
                        {
                            Id = 6,
                            Gender = "M",
                            Gender2 = "Female",
                            Married = true,
                            Name = "Henderson"
                        },
                        new
                        {
                            Id = 7,
                            Gender = "F",
                            Gender2 = "Female",
                            Married = false,
                            Name = "Robertson Naz"
                        },
                        new
                        {
                            Id = 8,
                            Gender = "F",
                            Gender2 = "Female",
                            Married = true,
                            Name = "Matipnur"
                        },
                        new
                        {
                            Id = 9,
                            Gender = "M",
                            Gender2 = "Female",
                            Married = true,
                            Name = "Thiago"
                        },
                        new
                        {
                            Id = 10,
                            Gender = "M",
                            Gender2 = "Female",
                            Married = true,
                            Name = "Alisson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
