// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectionResiliency.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221227191850_mig_1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "A101"
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "Migros"
                        },
                        new
                        {
                            PersonId = 3,
                            Name = "Şenol"
                        },
                        new
                        {
                            PersonId = 4,
                            Name = "Güneş"
                        },
                        new
                        {
                            PersonId = 5,
                            Name = "Alvaro"
                        },
                        new
                        {
                            PersonId = 6,
                            Name = "Sanchez"
                        },
                        new
                        {
                            PersonId = 7,
                            Name = "Gülüm"
                        },
                        new
                        {
                            PersonId = 8,
                            Name = "Jale"
                        },
                        new
                        {
                            PersonId = 9,
                            Name = "Ramiz"
                        },
                        new
                        {
                            PersonId = 10,
                            Name = "Dayı"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
